// Generated by sila2-codegen — do not edit.
#pragma once

#include "List.grpc.pb.h"
#include "../meta/ListMeta.h"
#include <sila/server/transport/GrpcTransport.h>
#include <sila/server/transport/InterceptorChain.h>
#include <sila/server/transport/SilaHandler.h>
#include <sila/server/transport/cloud/CloudHandlerRegistration.h>
#include <sila/server/CommandParameterValidator.h>
#include <sila/server/binary/BinaryParameterInterceptor.h>

namespace sila2::generated::list {
namespace proto = sila2::org::silastandard::tests::list::v1;

class ListServiceAdapter final : public proto::List::Service {
public:
    explicit ListServiceAdapter(const sila2::InterceptorChain* chain = nullptr)
        : chain_{chain}, validator_{kFdlXml, kFqi} {
        validated_onTestCommand = [this](const auto& request, auto& context, auto& sink) {
            // Resolve Binary Transfer UUID parameters to their assembled bytes
            // before validation and the handler, so the direct-gRPC and cloud
            // transports share one resolution point (Part B p57, S71).
            if (chain_ != nullptr && chain_->binaryStore != nullptr) {
                auto resolved = request;
                sila2::binary::resolveBinaryParameters(*chain_->binaryStore, &resolved);
                validator_.validate("TestCommand", resolved);
                onTestCommand(resolved, context, sink);
            } else {
                validator_.validate("TestCommand", request);
                onTestCommand(request, context, sink);
            }
        };
    }

    SilaHandler<proto::TestCommand_Parameters, proto::TestCommand_Responses> onTestCommand;
    SilaHandler<proto::Get_TestProperty_Parameters, proto::Get_TestProperty_Responses> onGetTestProperty;
    inline static const std::string kTestCommandFqi =
        std::string{"org.silastandard/tests/List/v1"} + "/Command/TestCommand";
    inline static const std::string kGet_TestPropertyFqi =
        std::string{"org.silastandard/tests/List/v1"} + "/Property/TestProperty";

    grpc::Status TestCommand(grpc::ServerContext* ctx,
                               const proto::TestCommand_Parameters* req,
                               proto::TestCommand_Responses* resp) override {
        GrpcUnaryResponseSink<proto::TestCommand_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, validated_onTestCommand, chain_, kTestCommandFqi, resp);
        return sink.status();
    }

    grpc::Status Get_TestProperty(grpc::ServerContext* ctx,
                               const proto::Get_TestProperty_Parameters* req,
                               proto::Get_TestProperty_Responses* resp) override {
        GrpcUnaryResponseSink<proto::Get_TestProperty_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, onGetTestProperty, chain_, kGet_TestPropertyFqi, resp);
        return sink.status();
    }

    void registerCloudHandlers(sila2::CloudEnvelopeRouter& router,
                               std::shared_ptr<ListServiceAdapter> self) {
        std::string fqi{"org.silastandard/tests/List/v1"};
        sila2::regCmd(router, fqi, "TestCommand", self,
                      &ListServiceAdapter::validated_onTestCommand);
        sila2::regProp(router, fqi, "TestProperty", self,
                       &ListServiceAdapter::onGetTestProperty);
    }

private:
    const sila2::InterceptorChain* chain_;
    sila2::CommandParameterValidator validator_;
    SilaHandler<proto::TestCommand_Parameters, proto::TestCommand_Responses> validated_onTestCommand;
};

}  // namespace sila2::generated::list
