// Generated by sila2-codegen — do not edit.
#include "MetadataMeta.h"

namespace sila2::generated::metadata {

// The XML must start right after the raw-string delimiter: an XML declaration
// preceded by a newline is not well-formed, and XSD-validating clients
// (sila2-python) reject the served FeatureDefinition outright.
const std::string_view kFdlXml = R"xml(<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" Originator="org.silastandard"
         Category="tests"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>Metadata</Identifier>
    <DisplayName>Metadata</DisplayName>
    <Description>Provides Metadata elements</Description>
    <Metadata>
        <Identifier>Meta1</Identifier>
        <DisplayName>Meta 1</DisplayName>
        <Description>First metadata</Description>
        <DataType>
            <Basic>String</Basic>
        </DataType>
    </Metadata>
    <Metadata>
        <Identifier>Meta2</Identifier>
        <DisplayName>Meta 2</DisplayName>
        <Description>Second metadata</Description>
        <DataType>
            <Basic>String</Basic>
        </DataType>
    </Metadata>
</Feature>
)xml";

}  // namespace sila2::generated::metadata
