// Generated by sila2-codegen — do not edit.
#pragma once

#include "Metadata.grpc.pb.h"
#include "../meta/MetadataMeta.h"
#include <sila/server/transport/GrpcTransport.h>
#include <sila/server/transport/InterceptorChain.h>
#include <sila/server/transport/SilaHandler.h>
#include <sila/server/transport/cloud/CloudHandlerRegistration.h>
#include <sila/server/CommandParameterValidator.h>
#include <sila/server/binary/BinaryParameterInterceptor.h>

namespace sila2::generated::metadata {
namespace proto = sila2::org::silastandard::tests::metadata::v1;

class MetadataServiceAdapter final : public proto::Metadata::Service {
public:
    explicit MetadataServiceAdapter(const sila2::InterceptorChain* chain = nullptr)
        : chain_{chain}, validator_{kFdlXml, kFqi} {
    }

    SilaHandler<proto::Get_FCPAffectedByMetadata_Meta1_Parameters, proto::Get_FCPAffectedByMetadata_Meta1_Responses> onGetFCPAffectedByMetadataMeta1;
    SilaHandler<proto::Get_FCPAffectedByMetadata_Meta2_Parameters, proto::Get_FCPAffectedByMetadata_Meta2_Responses> onGetFCPAffectedByMetadataMeta2;
    static constexpr std::string_view kGet_FCPAffectedByMetadata_Meta1Fqi = "org.silastandard/tests/Metadata/v1";
    static constexpr std::string_view kGet_FCPAffectedByMetadata_Meta2Fqi = "org.silastandard/tests/Metadata/v1";

    grpc::Status Get_FCPAffectedByMetadata_Meta1(grpc::ServerContext* ctx,
                               const proto::Get_FCPAffectedByMetadata_Meta1_Parameters* req,
                               proto::Get_FCPAffectedByMetadata_Meta1_Responses* resp) override {
        GrpcUnaryResponseSink<proto::Get_FCPAffectedByMetadata_Meta1_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, onGetFCPAffectedByMetadataMeta1, chain_, kGet_FCPAffectedByMetadata_Meta1Fqi, resp);
        return sink.status();
    }

    grpc::Status Get_FCPAffectedByMetadata_Meta2(grpc::ServerContext* ctx,
                               const proto::Get_FCPAffectedByMetadata_Meta2_Parameters* req,
                               proto::Get_FCPAffectedByMetadata_Meta2_Responses* resp) override {
        GrpcUnaryResponseSink<proto::Get_FCPAffectedByMetadata_Meta2_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, onGetFCPAffectedByMetadataMeta2, chain_, kGet_FCPAffectedByMetadata_Meta2Fqi, resp);
        return sink.status();
    }

    void registerCloudHandlers(sila2::CloudEnvelopeRouter& router,
                               std::shared_ptr<MetadataServiceAdapter> self) {
        std::string fqi{"org.silastandard/tests/Metadata/v1"};
        sila2::regProp(router, fqi, "FCPAffectedByMetadata_Meta1", self,
                       &MetadataServiceAdapter::onGetFCPAffectedByMetadataMeta1);
        sila2::regProp(router, fqi, "FCPAffectedByMetadata_Meta2", self,
                       &MetadataServiceAdapter::onGetFCPAffectedByMetadataMeta2);
    }

private:
    const sila2::InterceptorChain* chain_;
    sila2::CommandParameterValidator validator_;
};

}  // namespace sila2::generated::metadata
