// Generated by sila2-codegen — do not edit.
#pragma once

#include "NestedStructure.grpc.pb.h"
#include "../meta/NestedStructureMeta.h"
#include <sila/server/transport/GrpcTransport.h>
#include <sila/server/transport/InterceptorChain.h>
#include <sila/server/transport/SilaHandler.h>
#include <sila/server/transport/cloud/CloudHandlerRegistration.h>
#include <sila/server/CommandParameterValidator.h>
#include <sila/server/binary/BinaryParameterInterceptor.h>

namespace sila2::generated::nestedstructure {
namespace proto = sila2::org::silastandard::tests::nestedstructure::v1;

class NestedStructureServiceAdapter final : public proto::NestedStructure::Service {
public:
    explicit NestedStructureServiceAdapter(const sila2::InterceptorChain* chain = nullptr)
        : chain_{chain}, validator_{kFdlXml, kFqi} {
        validated_onTestCommand = [this](const auto& request, auto& context, auto& sink) {
            // Resolve Binary Transfer UUID parameters to their assembled bytes
            // before validation and the handler, so the direct-gRPC and cloud
            // transports share one resolution point (Part B p57, S71).
            if (chain_ != nullptr && chain_->binaryStore != nullptr) {
                auto resolved = request;
                sila2::binary::resolveBinaryParameters(*chain_->binaryStore, &resolved);
                validator_.validate("TestCommand", resolved);
                onTestCommand(resolved, context, sink);
            } else {
                validator_.validate("TestCommand", request);
                onTestCommand(request, context, sink);
            }
        };
    }

    SilaHandler<proto::TestCommand_Parameters, proto::TestCommand_Responses> onTestCommand;
    inline static const std::string kTestCommandFqi =
        std::string{"org.silastandard/tests/NestedStructure/v1"} + "/Command/TestCommand";

    grpc::Status TestCommand(grpc::ServerContext* ctx,
                               const proto::TestCommand_Parameters* req,
                               proto::TestCommand_Responses* resp) override {
        GrpcUnaryResponseSink<proto::TestCommand_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, validated_onTestCommand, chain_, kTestCommandFqi, resp);
        return sink.status();
    }

    void registerCloudHandlers(sila2::CloudEnvelopeRouter& router,
                               std::shared_ptr<NestedStructureServiceAdapter> self) {
        std::string fqi{"org.silastandard/tests/NestedStructure/v1"};
        sila2::regCmd(router, fqi, "TestCommand", self,
                      &NestedStructureServiceAdapter::validated_onTestCommand);
    }

private:
    const sila2::InterceptorChain* chain_;
    sila2::CommandParameterValidator validator_;
    SilaHandler<proto::TestCommand_Parameters, proto::TestCommand_Responses> validated_onTestCommand;
};

}  // namespace sila2::generated::nestedstructure
