// Generated by sila2-codegen — do not edit.
#pragma once

#include "NestedDataTypeDefinition.grpc.pb.h"
#include "../meta/NestedDataTypeDefinitionMeta.h"
#include <sila/server/transport/GrpcTransport.h>
#include <sila/server/transport/InterceptorChain.h>
#include <sila/server/transport/SilaHandler.h>
#include <sila/server/transport/cloud/CloudHandlerRegistration.h>
#include <sila/server/CommandParameterValidator.h>
#include <sila/server/binary/BinaryParameterInterceptor.h>

namespace sila2::generated::nesteddatatypedefinition {
namespace proto = sila2::org::silastandard::tests::nesteddatatypedefinition::v1;

class NestedDataTypeDefinitionServiceAdapter final : public proto::NestedDataTypeDefinition::Service {
public:
    explicit NestedDataTypeDefinitionServiceAdapter(const sila2::InterceptorChain* chain = nullptr)
        : chain_{chain}, validator_{kFdlXml, kFqi} {
    }


    void registerCloudHandlers(sila2::CloudEnvelopeRouter& router,
                               std::shared_ptr<NestedDataTypeDefinitionServiceAdapter> self) {
        std::string fqi{"org.silastandard/tests/NestedDataTypeDefinition/v1"};
    }

private:
    const sila2::InterceptorChain* chain_;
    sila2::CommandParameterValidator validator_;
};

}  // namespace sila2::generated::nesteddatatypedefinition
