// Generated by sila2-codegen — do not edit.
#include "NestedDataTypeDefinitionMeta.h"

namespace sila2::generated::nesteddatatypedefinition {

// The XML must start right after the raw-string delimiter: an XML declaration
// preceded by a newline is not well-formed, and XSD-validating clients
// (sila2-python) reject the served FeatureDefinition outright.
const std::string_view kFdlXml = R"xml(<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" Originator="org.silastandard"
         Category="tests"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>NestedDataTypeDefinition</Identifier>
    <DisplayName>Nested Data Type Definition</DisplayName>
    <Description>Provides nested DataTypeDefinitions</Description>
    <DataTypeDefinition>
        <Identifier>DataType1</Identifier>
        <DisplayName>Data Type 1</DisplayName>
        <Description>A data type</Description>
        <DataType>
            <DataTypeIdentifier>DataType2</DataTypeIdentifier>
        </DataType>
    </DataTypeDefinition>
    <DataTypeDefinition>
        <Identifier>DataType2</Identifier>
        <DisplayName>Data Type 2</DisplayName>
        <Description>Another data type</Description>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
    </DataTypeDefinition>
</Feature>
)xml";

}  // namespace sila2::generated::nesteddatatypedefinition
