// Generated by sila2-codegen — do not edit.
#pragma once

#include "ObservableCommandNoIntermediateResponse.grpc.pb.h"
#include "../meta/ObservableCommandNoIntermediateResponseMeta.h"
#include "SiLAFramework.pb.h"

#include <sila/server/transport/GrpcTransport.h>
#include <sila/server/transport/InterceptorChain.h>
#include <sila/server/transport/SilaHandler.h>
#include <sila/server/transport/cloud/CloudHandlerRegistration.h>
#include <sila/server/CommandParameterValidator.h>
#include <sila/server/binary/BinaryParameterInterceptor.h>

namespace sila2::generated::observablecommandnointermediateresponse {
namespace proto = sila2::org::silastandard::tests::observablecommandnointermediateresponse::v1;

class ObservableCommandNoIntermediateResponseServiceAdapter final : public proto::ObservableCommandNoIntermediateResponse::Service {
public:
    explicit ObservableCommandNoIntermediateResponseServiceAdapter(const sila2::InterceptorChain* chain = nullptr)
        : chain_{chain}, validator_{kFdlXml, kFqi} {
        validated_onTestCommand = [this](const auto& request, auto& context, auto& sink) {
            // Resolve Binary Transfer UUID parameters to their assembled bytes
            // before validation and the handler, so the direct-gRPC and cloud
            // transports share one resolution point (Part B p57, S71).
            if (chain_ != nullptr && chain_->binaryStore != nullptr) {
                auto resolved = request;
                sila2::binary::resolveBinaryParameters(*chain_->binaryStore, &resolved);
                validator_.validate("TestCommand", resolved);
                onTestCommand(resolved, context, sink);
            } else {
                validator_.validate("TestCommand", request);
                onTestCommand(request, context, sink);
            }
        };
    }

    SilaHandler<proto::TestCommand_Parameters, sila2::org::silastandard::CommandConfirmation> onTestCommand;
    SilaHandler<sila2::org::silastandard::CommandExecutionUUID, sila2::org::silastandard::ExecutionInfo> onTestCommandInfo;
    SilaHandler<sila2::org::silastandard::CommandExecutionUUID, proto::TestCommand_Responses> onTestCommandResult;
    inline static const std::string kTestCommandFqi =
        std::string{"org.silastandard/tests/ObservableCommandNoIntermediateResponse/v1"} + "/Command/TestCommand";
    inline static const std::string kTestCommand_InfoFqi =
        std::string{"org.silastandard/tests/ObservableCommandNoIntermediateResponse/v1"} + "/Command/TestCommand";
    inline static const std::string kTestCommand_ResultFqi =
        std::string{"org.silastandard/tests/ObservableCommandNoIntermediateResponse/v1"} + "/Command/TestCommand";

    grpc::Status TestCommand(grpc::ServerContext* ctx,
                               const proto::TestCommand_Parameters* req,
                               sila2::org::silastandard::CommandConfirmation* resp) override {
        GrpcUnaryResponseSink<sila2::org::silastandard::CommandConfirmation> sink(resp);
        dispatchToHandler(ctx, *req, sink, validated_onTestCommand, chain_, kTestCommandFqi, resp);
        return sink.status();
    }

    grpc::Status TestCommand_Info(grpc::ServerContext* ctx,
                               const sila2::org::silastandard::CommandExecutionUUID* req,
                               grpc::ServerWriter<sila2::org::silastandard::ExecutionInfo>* writer) override {
        GrpcStreamResponseSink<sila2::org::silastandard::ExecutionInfo> sink(writer);
        dispatchToHandler(ctx, *req, sink, onTestCommandInfo, chain_, kTestCommand_InfoFqi);
        return sink.status();
    }

    grpc::Status TestCommand_Result(grpc::ServerContext* ctx,
                               const sila2::org::silastandard::CommandExecutionUUID* req,
                               proto::TestCommand_Responses* resp) override {
        GrpcUnaryResponseSink<proto::TestCommand_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, onTestCommandResult, chain_, kTestCommand_ResultFqi, resp);
        return sink.status();
    }

    void registerCloudHandlers(sila2::CloudEnvelopeRouter& router,
                               std::shared_ptr<ObservableCommandNoIntermediateResponseServiceAdapter> self) {
        std::string fqi{"org.silastandard/tests/ObservableCommandNoIntermediateResponse/v1"};
        sila2::regObsCmd(router, fqi, "TestCommand", self,
                         &ObservableCommandNoIntermediateResponseServiceAdapter::validated_onTestCommand,
                         &ObservableCommandNoIntermediateResponseServiceAdapter::onTestCommandInfo,
                         &ObservableCommandNoIntermediateResponseServiceAdapter::onTestCommandResult);
    }

private:
    const sila2::InterceptorChain* chain_;
    sila2::CommandParameterValidator validator_;
    SilaHandler<proto::TestCommand_Parameters, sila2::org::silastandard::CommandConfirmation> validated_onTestCommand;
};

}  // namespace sila2::generated::observablecommandnointermediateresponse
