// Generated by sila2-codegen — do not edit.
#pragma once

#include "ObservableBasic.grpc.pb.h"
#include "../meta/ObservableBasicMeta.h"
#include "SiLAFramework.pb.h"

#include <sila/server/transport/GrpcTransport.h>
#include <sila/server/transport/InterceptorChain.h>
#include <sila/server/transport/SilaHandler.h>
#include <sila/server/transport/cloud/CloudHandlerRegistration.h>
#include <sila/server/CommandParameterValidator.h>
#include <sila/server/binary/BinaryParameterInterceptor.h>

namespace sila2::generated::observablebasic {
namespace proto = sila2::org::silastandard::tests::observablebasic::v1;

class ObservableBasicServiceAdapter final : public proto::ObservableBasic::Service {
public:
    explicit ObservableBasicServiceAdapter(const sila2::InterceptorChain* chain = nullptr)
        : chain_{chain}, validator_{kFdlXml, kFqi} {
        validated_onTestCommand = [this](const auto& request, auto& context, auto& sink) {
            // Resolve Binary Transfer UUID parameters to their assembled bytes
            // before validation and the handler, so the direct-gRPC and cloud
            // transports share one resolution point (Part B p57, S71).
            if (chain_ != nullptr && chain_->binaryStore != nullptr) {
                auto resolved = request;
                sila2::binary::resolveBinaryParameters(*chain_->binaryStore, &resolved);
                validator_.validate("TestCommand", resolved);
                onTestCommand(resolved, context, sink);
            } else {
                validator_.validate("TestCommand", request);
                onTestCommand(request, context, sink);
            }
        };
    }

    SilaHandler<proto::TestCommand_Parameters, sila2::org::silastandard::CommandConfirmation> onTestCommand;
    SilaHandler<sila2::org::silastandard::CommandExecutionUUID, sila2::org::silastandard::ExecutionInfo> onTestCommandInfo;
    SilaHandler<sila2::org::silastandard::CommandExecutionUUID, proto::TestCommand_IntermediateResponses> onTestCommandIntermediate;
    SilaHandler<sila2::org::silastandard::CommandExecutionUUID, proto::TestCommand_Responses> onTestCommandResult;
    SilaHandler<proto::Subscribe_TestProperty_Parameters, proto::Subscribe_TestProperty_Responses> onSubscribeTestProperty;
    inline static const std::string kTestCommandFqi =
        std::string{"org.silastandard/tests/ObservableBasic/v1"} + "/Command/TestCommand";
    inline static const std::string kTestCommand_InfoFqi =
        std::string{"org.silastandard/tests/ObservableBasic/v1"} + "/Command/TestCommand";
    inline static const std::string kTestCommand_IntermediateFqi =
        std::string{"org.silastandard/tests/ObservableBasic/v1"} + "/Command/TestCommand";
    inline static const std::string kTestCommand_ResultFqi =
        std::string{"org.silastandard/tests/ObservableBasic/v1"} + "/Command/TestCommand";
    inline static const std::string kSubscribe_TestPropertyFqi =
        std::string{"org.silastandard/tests/ObservableBasic/v1"} + "/Property/TestProperty";

    grpc::Status TestCommand(grpc::ServerContext* ctx,
                               const proto::TestCommand_Parameters* req,
                               sila2::org::silastandard::CommandConfirmation* resp) override {
        GrpcUnaryResponseSink<sila2::org::silastandard::CommandConfirmation> sink(resp);
        dispatchToHandler(ctx, *req, sink, validated_onTestCommand, chain_, kTestCommandFqi, resp);
        return sink.status();
    }

    grpc::Status TestCommand_Info(grpc::ServerContext* ctx,
                               const sila2::org::silastandard::CommandExecutionUUID* req,
                               grpc::ServerWriter<sila2::org::silastandard::ExecutionInfo>* writer) override {
        GrpcStreamResponseSink<sila2::org::silastandard::ExecutionInfo> sink(writer);
        dispatchToHandler(ctx, *req, sink, onTestCommandInfo, chain_, kTestCommand_InfoFqi);
        return sink.status();
    }

    grpc::Status TestCommand_Intermediate(grpc::ServerContext* ctx,
                               const sila2::org::silastandard::CommandExecutionUUID* req,
                               grpc::ServerWriter<proto::TestCommand_IntermediateResponses>* writer) override {
        GrpcStreamResponseSink<proto::TestCommand_IntermediateResponses> sink(writer);
        dispatchToHandler(ctx, *req, sink, onTestCommandIntermediate, chain_, kTestCommand_IntermediateFqi);
        return sink.status();
    }

    grpc::Status TestCommand_Result(grpc::ServerContext* ctx,
                               const sila2::org::silastandard::CommandExecutionUUID* req,
                               proto::TestCommand_Responses* resp) override {
        GrpcUnaryResponseSink<proto::TestCommand_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, onTestCommandResult, chain_, kTestCommand_ResultFqi, resp);
        return sink.status();
    }

    grpc::Status Subscribe_TestProperty(grpc::ServerContext* ctx,
                               const proto::Subscribe_TestProperty_Parameters* req,
                               grpc::ServerWriter<proto::Subscribe_TestProperty_Responses>* writer) override {
        GrpcStreamResponseSink<proto::Subscribe_TestProperty_Responses> sink(writer);
        dispatchToHandler(ctx, *req, sink, onSubscribeTestProperty, chain_, kSubscribe_TestPropertyFqi);
        return sink.status();
    }

    void registerCloudHandlers(sila2::CloudEnvelopeRouter& router,
                               std::shared_ptr<ObservableBasicServiceAdapter> self) {
        std::string fqi{"org.silastandard/tests/ObservableBasic/v1"};
        sila2::regObsCmd(router, fqi, "TestCommand", self,
                         &ObservableBasicServiceAdapter::validated_onTestCommand,
                         &ObservableBasicServiceAdapter::onTestCommandInfo,
                         &ObservableBasicServiceAdapter::onTestCommandIntermediate,
                         &ObservableBasicServiceAdapter::onTestCommandResult);
        // The Subscribe_ handler runs on a router pump thread that is joined at
        // router teardown, so it must end on cancellation -- register
        // ctx.onCancellation to wake a blocked wait, or poll ctx.isCancelled().
        // Same contract the direct-gRPC streaming path and _Intermediate impose.
        sila2::regObsProp(router, fqi, "TestProperty", self,
                          &ObservableBasicServiceAdapter::onSubscribeTestProperty);
    }

private:
    const sila2::InterceptorChain* chain_;
    sila2::CommandParameterValidator validator_;
    SilaHandler<proto::TestCommand_Parameters, sila2::org::silastandard::CommandConfirmation> validated_onTestCommand;
};

}  // namespace sila2::generated::observablebasic
