// Generated by sila2-codegen — do not edit.
#pragma once

#include <string_view>

namespace sila2::generated::observablebasic {

// Fully Qualified Identifier
inline constexpr std::string_view kFqi =
    "org.silastandard/tests/ObservableBasic/v1";

// Feature version
inline constexpr std::string_view kFeatureVersion = "1.0";

// FDL XML original (defined in ObservableBasicMeta.cc)
extern const std::string_view kFdlXml;

}  // namespace sila2::generated::observablebasic
