// Generated by sila2-codegen — do not edit.
#pragma once

#include "SettingsService.grpc.pb.h"
#include "../meta/SettingsServiceMeta.h"
#include <sila/server/transport/GrpcTransport.h>
#include <sila/server/transport/InterceptorChain.h>
#include <sila/server/transport/SilaHandler.h>
#include <sila/server/transport/cloud/CloudHandlerRegistration.h>
#include <sila/server/CommandParameterValidator.h>
#include <sila/server/binary/BinaryParameterInterceptor.h>

namespace sila2::generated::settingsservice {
namespace proto = sila2::org::silastandard::examples::settingsservice::v1;

class SettingsServiceServiceAdapter final : public proto::SettingsService::Service {
public:
    explicit SettingsServiceServiceAdapter(const sila2::InterceptorChain* chain = nullptr)
        : chain_{chain}, validator_{kFdlXml, kFqi} {
        validated_onSetSerialPort = [this](const auto& request, auto& context, auto& sink) {
            // Resolve Binary Transfer UUID parameters to their assembled bytes
            // before validation and the handler, so the direct-gRPC and cloud
            // transports share one resolution point (Part B p57, S71).
            if (chain_ != nullptr && chain_->binaryStore != nullptr) {
                auto resolved = request;
                sila2::binary::resolveBinaryParameters(*chain_->binaryStore, &resolved);
                validator_.validate("SetSerialPort", resolved);
                onSetSerialPort(resolved, context, sink);
            } else {
                validator_.validate("SetSerialPort", request);
                onSetSerialPort(request, context, sink);
            }
        };
    }

    SilaHandler<proto::SetSerialPort_Parameters, proto::SetSerialPort_Responses> onSetSerialPort;
    SilaHandler<proto::Get_SerialPort_Parameters, proto::Get_SerialPort_Responses> onGetSerialPort;
    inline static const std::string kSetSerialPortFqi =
        std::string{"org.silastandard/examples/SettingsService/v1"} + "/Command/SetSerialPort";
    inline static const std::string kGet_SerialPortFqi =
        std::string{"org.silastandard/examples/SettingsService/v1"} + "/Property/SerialPort";

    grpc::Status SetSerialPort(grpc::ServerContext* ctx,
                               const proto::SetSerialPort_Parameters* req,
                               proto::SetSerialPort_Responses* resp) override {
        GrpcUnaryResponseSink<proto::SetSerialPort_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, validated_onSetSerialPort, chain_, kSetSerialPortFqi, resp);
        return sink.status();
    }

    grpc::Status Get_SerialPort(grpc::ServerContext* ctx,
                               const proto::Get_SerialPort_Parameters* req,
                               proto::Get_SerialPort_Responses* resp) override {
        GrpcUnaryResponseSink<proto::Get_SerialPort_Responses> sink(resp);
        dispatchToHandler(ctx, *req, sink, onGetSerialPort, chain_, kGet_SerialPortFqi, resp);
        return sink.status();
    }

    void registerCloudHandlers(sila2::CloudEnvelopeRouter& router,
                               std::shared_ptr<SettingsServiceServiceAdapter> self) {
        std::string fqi{"org.silastandard/examples/SettingsService/v1"};
        sila2::regCmd(router, fqi, "SetSerialPort", self,
                      &SettingsServiceServiceAdapter::validated_onSetSerialPort);
        sila2::regProp(router, fqi, "SerialPort", self,
                       &SettingsServiceServiceAdapter::onGetSerialPort);
    }

private:
    const sila2::InterceptorChain* chain_;
    sila2::CommandParameterValidator validator_;
    SilaHandler<proto::SetSerialPort_Parameters, proto::SetSerialPort_Responses> validated_onSetSerialPort;
};

}  // namespace sila2::generated::settingsservice
