// Generated by sila2-codegen — do not edit.
#include "SimpleStructureMeta.h"

namespace sila2::generated::simplestructure {

// The XML must start right after the raw-string delimiter: an XML declaration
// preceded by a newline is not well-formed, and XSD-validating clients
// (sila2-python) reject the served FeatureDefinition outright.
const std::string_view kFdlXml = R"xml(<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" Originator="org.silastandard"
         Category="tests"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>SimpleStructure</Identifier>
    <DisplayName>Simple Structure</DisplayName>
    <Description>Provides an unobservable command with a simple structure response data type</Description>
    <Command>
        <Identifier>TestCommand</Identifier>
        <DisplayName>Test Command</DisplayName>
        <Description>Command for testing</Description>
        <Observable>No</Observable>
        <Response>
            <Identifier>Response1</Identifier>
            <DisplayName>Response 1</DisplayName>
            <Description>First response</Description>
            <DataType>
                <Structure>
                    <Element>
                        <Identifier>Element1</Identifier>
                        <DisplayName>Element 1</DisplayName>
                        <Description>First element</Description>
                        <DataType>
                            <Basic>Integer</Basic>
                        </DataType>
                    </Element>
                    <Element>
                        <Identifier>Element2</Identifier>
                        <DisplayName>Element 2</DisplayName>
                        <Description>Second element</Description>
                        <DataType>
                            <Basic>String</Basic>
                        </DataType>
                    </Element>
                </Structure>
            </DataType>
        </Response>
    </Command>
</Feature>
)xml";

}  // namespace sila2::generated::simplestructure
